SalaryCapGame/Controllers/OwnersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SalaryCapData;
using SalaryCapData.ConsumeJson.Models.Game;
using SalaryCapData.Interfaces;
using SalaryCapData.Models;
using SalaryCapGame.ViewModels;
using SalaryCapGame.ViewModels.Dashboard;
using SalaryCapGame.ViewModels.Player;
using static SalaryCapData.ConsumeJson.Models.Game.HitterPoints;

namespace SalaryCapGame.Controllers
{
	public class OwnersController : Controller
	{
		private readonly IOwner _owners;
		private readonly ILeague _leagues;
		private readonly IPlayer _players;

		public OwnersController( IOwner owners, ILeague leagues, IPlayer players )
		{
			_owners = owners;
			_leagues = leagues;
			_players = players;
		}

		public IActionResult List( int id )
		{

			var owner = _owners.Get( id );
			var model = new OwnerIndexListingModel
			{
				Id = owner.Id,
				FirstName = owner.FirstName,
				LastName = owner.LastName,
				ImageUrl = owner.ImageUrl,
				Franchises = owner.Franchises,
				Leagues = owner.Leagues
			};

			return View( model );
		}
		// GET: Owners
		public IActionResult OwnersList()
		{

			var owners = _owners.GetAll();
			var listingResult = owners.Select( o => new OwnerIndexListingModel
			{
				Id = o.Id,
				Email = o.Email,
				FirstName = o.FirstName,
				LastName = o.LastName,
				ImageUrl = o.ImageUrl,
				Franchises = o.Franchises,
				Leagues = o.Leagues
			} ).ToList();
			var model = new OwnerIndexModel { Owners = listingResult };
			return View( model );
		}

		public PartialViewResult View( int id )
		{
			var owner = _owners.Get( id );

			_leagues.AssignFranchiseLeagues( owner.Franchises );
			var model = new FranchiseMenuModel
			{
				OwnerId = owner.Id,
				Franchises = owner.Franchises,
				Leagues = owner.Leagues
			};

			return PartialView( "~/Views/Partial/Franchise/_View.cshtml", model );
		}

		// GET: Owners/Details/5
		public IActionResult Details( int id )
		{
			if ( id == 0 )
			{
				return NotFound();
			}

			var owner = _owners.Get( id );
			if ( owner == null )
			{
				return NotFound();
			}

			OwnerIndexListingModel ownerModel = GetOwnerIndexListingModel( id, owner );
			//List<PlayerIndexListingModel> playersModel = GetPlayersIndexListingModel( id );
			StatsIndexListModel statsIndexListModel = GetAllStats();
			foreach ( var p in statsIndexListModel.HitterStats )
			{
				p.Player.TotalPoints = p.Player.GetHitterPoints();
			}

			foreach ( var p in statsIndexListModel.PitcherStats )
			{
				p.Player.TotalPoints = p.Player.GetPitcherPoints();
			}
			// var playerModel = new PlayerIndexModel { Players = playersModel };
			var dashboardModel = new DashboardViewModel
			{
				OwnerIndex = ownerModel,
				PlayerStats = statsIndexListModel,
			};

			return View( "List", dashboardModel );
		}

		private StatsIndexListModel GetAllStats()
		{

			IEnumerable<HitterStats> hitterStats = _players.GetHitterStats( 25 );
			IEnumerable<PitcherStats> pitcherStats = _players.GetPitcherStats( 25 );

			StatsIndexListModel statsModel = new StatsIndexListModel
			{
				HitterStats = hitterStats,
				PitcherStats = pitcherStats
			};

			return (statsModel);
		}



		//private int GetTotalPoints( Player player )
		//{
		//	if ( player.Position == "P" )
		//		return (GetTotalPitcherPoints( player.PictherStats ));
		//	else
		//		return (GetTotalHitterPoints( player.HitterStats ));
		//}

		//private int GetTotalPitcherPoints( PitcherStats pictherStats )
		//{
		//	return 100;

		//}

		//private int GetTotalHitterPoints( HitterStats hitterStats )
		//{
		//	int hitPoints = hitterStats.Hits * (int)HitterPointValues.Hit;
		//	int runPoints = hitterStats.Runs * (int)HitterPointValues.Run;
		//	int doublePoints = hitterStats.Doubles * (int)HitterPointValues.Double;
		//	int triplePoints = hitterStats.Doubles * (int)HitterPointValues.Triple;
		//	int homeRunPoints = hitterStats.Doubles * (int)HitterPointValues.HomeRun;
		//	int rbiPoints = hitterStats.Doubles * (int)HitterPointValues.RBI;
		//	int walkPoints = hitterStats.Doubles * (int)HitterPointValues.Walk;
		//	int stolenBasePoints = hitterStats.Doubles * (int)HitterPointValues.StolenBase;
		//	int strikeoutPoints = hitterStats.Doubles * (int)HitterPointValues.Strikeout;
		//	int sacrificePoints = hitterStats.Sacrifices;

		//	return (hitPoints
		//			+ runPoints
		//			+ doublePoints
		//			+ triplePoints
		//			+ homeRunPoints
		//			+ rbiPoints
		//			+ walkPoints
		//			+ stolenBasePoints
		//			+ sacrificePoints
		//			+ strikeoutPoints);

		//}

		private List<PlayerIndexListingModel> GetPlayersIndexListingModel( int id )
		{
			IEnumerable<Player> players = _players.GetAll();

			if ( players == null )
				return null;

			var results = players.Select( p => new PlayerIndexListingModel
			{
				PlayerId = p.Id,
				FirstName = p.FirstName,
				LastName = p.LastName,
				Position = p.Position,
				Team = p.Team,
				Value = p.InitialValue,
				HitterStats = p.HitterStats,
				PitcherStats = p.PitcherStats,
				//TotalPoints = GetTotalPoints( p )
			} ).ToList();

			return results;
		}


		private OwnerIndexListingModel GetOwnerIndexListingModel( int id, Owner owner )
		{
			var ownerModel = new OwnerIndexListingModel
			{
				Id = owner.Id,
				FirstName = owner.FirstName,
				LastName = owner.LastName,
				ImageUrl = owner.ImageUrl,
				Franchises = owner.Franchises,
				Leagues = owner.Leagues

			};

			return ownerModel;
		}


		// GET: Owners/Create
		public IActionResult Create()
		{
			return View();
		}

		// POST: Owners/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create( [Bind( "Id,FirstName,LastName,Email,ImageUrl,DateCreated,DateModified" )] Owner owner )
		{
			if ( ModelState.IsValid )
			{
				_owners.Add( owner );
				return RedirectToAction( nameof( OwnersList ) );
			}
			return View( owner );
		}

		// GET: Owners/Edit/5
		public IActionResult Edit( int id )
		{
			if ( id == 0 )
			{
				return NotFound();
			}

			var owner = _owners.Get( id );
			if ( owner == null )
			{
				return NotFound();
			}
			return View( owner );
		}

		// POST: Owners/Edit/5
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit( int id, [Bind( "Id,FirstName,LastName,Email,ImageUrl,DateCreated,DateModified" )] Owner owner )
		{
			if ( id != owner.Id )
			{
				return NotFound();
			}

			if ( ModelState.IsValid )
			{
				try
				{
					_owners.Update( owner );
				}
				catch ( DbUpdateConcurrencyException )
				{
					if ( !OwnerExists( owner.Id ) )
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction( nameof( OwnersList ) );
			}
			return View( owner );
		}

		//// GET: Owners/Delete/5
		//public async Task<IActionResult> Delete(int? id)
		//{
		//    if (id == null)
		//    {
		//        return NotFound();
		//    }

		//    var owner = await _context.Owners
		//        .SingleOrDefaultAsync(m => m.Id == id);
		//    if (owner == null)
		//    {
		//        return NotFound();
		//    }

		//    return View(owner);
		//}

		//// POST: Owners/Delete/5
		//[HttpPost, ActionName("Delete")]
		//[ValidateAntiForgeryToken]
		//public async Task<IActionResult> DeleteConfirmed(int id)
		//{
		//    var owner = await _context.Owners.SingleOrDefaultAsync(m => m.Id == id);
		//    _context.Owners.Remove(owner);
		//    await _context.SaveChangesAsync();
		//    return RedirectToAction(nameof(Index));
		//}

		private bool OwnerExists( int id )
		{
			return _owners.Get( id ) != null;
		}
	}


}

SalaryCapGame/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData[ "Title" ] - Salary Cap Game</title>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<link href="~/css/site.css" rel="stylesheet">
</head>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand"> Salary Cap Games</a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li><a asp-area="" asp-controller="Owners" asp-action="Index">Owners</a></li>
					<li><a asp-area="" asp-controller="Leagues" asp-action="Index">Leagues</a></li>
					<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
					<li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
					<li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
				</ul>
			</div>
		</div>
	</nav>
	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p>&copy; 2017 - Salary Cap Games</p>
		</footer>
	</div>

	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

	@RenderSection( "scripts", required: false )
</body>
</html>

SalaryCapGame/Views/Shared/_Footer.cshtml
<div class="footer">
	&copy;2018 Salary Cap Game. All rights reserved.
</div>

SalaryCapGame/Views/Shared/_Header.cshtml
<div class="header">This is header text.</div>

SalaryCapGame/Views/Shared/_Header2.cshtml
<div id="header">Creating a Consistent Look</div>

SalaryCapGame/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.ViewFeatures
@using SalaryCapGame.ViewModels
@model SalaryCapGame.ViewModels.DashboardViewModel



<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />
	<meta name="viewport" content="width=device-width , initial-scale=1">

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0/css/bootstrap.css">
	<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.10.16/fh-3.1.3/r-2.2.1/sl-1.2.5/datatables.min.css" />
	@*
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />*@
	<title>Dashboard Template for Bootstrap</title>


	<style>

		body {
			font-family: "Lato", sans-serif;
		}

		.sidenav {
			height: 100%;
			width: 0;
			position: fixed;
			z-index: 1;
			top: 0;
			left: 0;
			background-color: #111;
			overflow-x: hidden;
			transition: 0.5s;
			padding-top: 60px;
		}

			.sidenav a {
				padding: 8px 8px 8px 32px;
				text-decoration: none;
				font-size: 25px;
				color: #818181;
				display: block;
				transition: 0.3s;
			}

				.sidenav a:hover {
					color: #f1f1f1;
				}

			.sidenav .closebtn {
				position: absolute;
				top: 0;
				right: 25px;
				font-size: 36px;
				margin-left: 50px;
			}

		#main {
			transition: margin-left .5s;
			padding: 16px;
		}

		@@media screen and (max-height: 450px) {
			.sidenav {
				padding-top: 15px;
			}

				.sidenav a {
					font-size: 18px;
				}
		}

		td.details-control {
			text-align: center;
			color: forestgreen;
			cursor: pointer;
		}

		tr.dropPlayer td.details-control {
			text-align: center;
			color: red;
		}

		.padding-0 {
			padding-right: 0;
			padding-left: 0;
		}

		.mb-0 > a {
			display: block;
			position: relative;
		}

			.mb-0 > a:after {
				content: "\f078"; /* fa-chevron-down */
				font-family: 'FontAwesome';
				position: absolute;
				right: 0;
			}

			.mb-0 > a[aria-expanded="true"]:after {
				content: "\f077"; /* fa-chevron-up */
			}
	</style>
	<!-- Bootstrap core CSS -->
	<!-- Custom styles for this template -->
	<link href="~/css/chart.css" rel="stylesheet">

	@*
		<link href="~/css/sortable.css" rel="stylesheet">*@

	@*
		<link href="~/css/dashboard.css" rel="stylesheet">*@

	@*
		<link rel="stylesheet" href="~/css/sidebar.css">*@

	@*<link href="~/css/accordion.css" rel="stylesheet">*@

	@*
		<link href="~/css/sidenav.css" rel="stylesheet">*@
	@*
		<script type="text/javascript" src="~/js/sortable.js" async></script>*@

	@*@RenderSection( "MyPlayers", false );*@



</head>

<body>
	@*<nav class="navbar">
			<span class="open-slide">
				<a href="#" onclick="openSlideMenu()">
					<svg height="30" width="30">
						<path d="M0,5 30,5" stroke="#fff" stroke-width="5" />
						<path d="M0,14 30,14" stroke="#fff" stroke-width="5" />
						<path d="M0,23 30,23" stroke="#fff" stroke-width="5" />
					</svg>
				</a>
			</span>
			<ul class="navbar-nav">
				<li>
					<a href="#Home">W</a>
				</li>
				<li>
					<a href="#">About</a>
				</li>
				<li>
					<a href="#">Services</a>
				</li>
			</ul>
		</nav>*@

	<div id="mySidenav" class="sidenav">
		<a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
		<div class="list-group border-0 card text-center text-md-left">
			<a href="#menu1" class="list-group-item d-inline-block collapsed" data-toggle="collapse" data-parent="#sidebar" aria-expanded="false">
				<i class="fa fa-dashboard"></i>
				<span class="d-none d-md-inline">Item 1</span>
			</a>
			<div class="collapse" id="menu1">
				<a href="#menu1sub1" class="list-group-item" data-toggle="collapse" aria-expanded="false">Subitem 1 </a>
				<div class="collapse" id="menu1sub1">
					<a href="#demo" class="list-group-item" data-parent="#menu1sub1">Demo</a>
					<a href="#demo2" class="list-group-item" data-parent="#menu1sub1">Demo 2 b</a>
					<a href="#menu1sub1sub1" class="list-group-item" data-toggle="collapse" aria-expanded="false">Subitem 3 c </a>
					<div class="collapse" id="menu1sub1sub1">
						<a href="#" class="list-group-item" data-parent="#menu1sub1sub1">Subitem 3 c.1</a>
						<a href="#" class="list-group-item" data-parent="#menu1sub1sub1">Subitem 3 c.2</a>
					</div>
					<a href="#" class="list-group-item" data-parent="#menu1sub1">Subitem 4 d</a>
					<a href="#menu1sub1sub2" class="list-group-item" data-toggle="collapse" aria-expanded="false">Subitem 5 e </a>
					<div class="collapse" id="menu1sub1sub2">
						<a href="#" class="list-group-item" data-parent="#menu1sub1sub2">Subitem 5 e.1</a>
						<a href="#" class="list-group-item" data-parent="#menu1sub1sub2">Subitem 5 e.2</a>
					</div>
				</div>
				<a href="#" class="list-group-item" data-parent="#menu1">Subitem 2</a>
				<a href="#" class="list-group-item" data-parent="#menu1">Subitem 3</a>
			</div>

			<a href="#" class="list-group-item d-inline-block collapsed" data-parent="#sidebar">
				<i class="fa fa-heart"></i>
				<span class="d-none d-md-inline">Item 2</span>
			</a>
			<a href="#" class="list-group-item d-inline-block collapsed" data-parent="#sidebar">
				<i class="fa fa-list"></i>
				<span class="d-none d-md-inline">Item 3</span>
			</a>
			<a href="#" class="list-group-item d-inline-block collapsed" data-parent="#sidebar">
				<i class="fa fa-clock-o"></i>
				<span class="d-none d-md-inline">Link</span>
			</a>
			<a href="#" class="list-group-item d-inline-block collapsed" data-parent="#sidebar">
				<i class="fa fa-th"></i>
				<span class="d-none d-md-inline">Link</span>
			</a>
			<a href="#" class="list-group-item d-inline-block collapsed" data-parent="#sidebar">
				<i class="fa fa-gear"></i>
				<span class="d-none d-md-inline">Link</span>
			</a>
			<a href="#" class="list-group-item d-inline-block collapsed" data-parent="#sidebar">
				<i class="fa fa-calendar"></i>
				<span class="d-none d-md-inline">Link</span>
			</a>
			<a href="#" class="list-group-item d-inline-block collapsed" data-parent="#sidebar">
				<i class="fa fa-envelope"></i>
				<span class="d-none d-md-inline">Link</span>
			</a>
			<a href="#" class="list-group-item d-inline-block collapsed" data-parent="#sidebar">
				<i class="fa fa-bar-chart-o"></i>
				<span class="d-none d-md-inline">Link</span>
			</a>
			<a href="#" class="list-group-item d-inline-block collapsed" data-parent="#sidebar">
				<i class="fa fa-star"></i>
				<span class="d-none d-md-inline">Link</span>
			</a>
		</div>
	</div>

	<main id="main">
		@*<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
				<h1 class="h2">Dashboard</h1>
			</div>*@
		<span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; open</span>
		<div class="d-flex flex-column col-md-5">
			@RenderSection( "FranchiseMenu" )
			@*@RenderBody()*@
		</div>


		<div id="accordion">
			<div class="card">
				<div class="card-header" id="heading-1">
					<h5 class="mb-0">
						<a role="button" data-toggle="collapse" href="#collapse-1" aria-expanded="true" aria-controls="collapse-1">
							My Team
						</a>
					</h5>
				</div>
				<div id="collapse-1" class="collapse show" data-parent="#accordion" aria-labelledby="heading-1">
					<div class="card-body">

						<div id="accordion-1">
							<div class="card">
								<div class="card-header" id="heading-1-1">
									<h5 class="mb-0">
										<a class="collapsed" role="button" data-toggle="collapse" href="#collapse-1-1" aria-expanded="false" aria-controls="collapse-1-1">
											Hitters
										</a>
									</h5>
								</div>
								<div id="collapse-1-1" class="collapse" data-parent="#accordion-1" aria-labelledby="heading-1-1">
									<div class="card-body">
										@RenderSection( "MyHitters" )

									</div>
								</div>
							</div>
							<div class="card">
								<div class="card-header" id="heading-1-2">
									<h5 class="mb-0">
										<a class="collapsed" role="button" data-toggle="collapse" href="#collapse-1-2" aria-expanded="false" aria-controls="collapse-1-2">
											Pitchers
										</a>
									</h5>
								</div>
								<div id="collapse-1-2" class="collapse" data-parent="#accordion-1" aria-labelledby="heading-1-2">
									<div class="card-body">
										@RenderSection( "MyPitchers" )
									</div>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>
			<div class="card">
				<div class="card-header" id="heading-2">
					<h5 class="mb-0">
						<a class="collapsed" role="button" data-toggle="collapse" href="#collapse-2" aria-expanded="false" aria-controls="collapse-2">
							Trade Players
						</a>
					</h5>
				</div>
				<div id="collapse-2" class="collapse" data-parent="#accordion" aria-labelledby="heading-2">
					<div class="card-body">

						<div id="accordion-2">
							<div class="card">
								<div class="card-header" id="heading-2-1">
									<h5 class="mb-0">
										<a class="collapsed" role="button" data-toggle="collapse" href="#collapse-2-1" aria-expanded="false" aria-controls="collapse-2-1">
											Hitters
										</a>
									</h5>
								</div>
								<div id="collapse-2-1" class="collapse" data-parent="#accordion-2" aria-labelledby="heading-2-1">
									<div class="card-body">
										@RenderSection( "HitterList" )

									</div>
								</div>
							</div>
							<div class="card">
								<div class="card-header" id="heading-2-2">
									<h5 class="mb-0">
										<a class="collapsed" role="button" data-toggle="collapse" href="#collapse-2-2" aria-expanded="false" aria-controls="collapse-2-2">
											Pitchers
										</a>
									</h5>
								</div>
								<div id="collapse-2-2" class="collapse" data-parent="#accordion-2" aria-labelledby="heading-2-2">
									<div class="card-body">
										@RenderSection( "PitcherList" )
									</div>
								</div>
							</div>
						</div>

					</div>
				</div>
			</div>

		</div>


	</main>



	<!-- Bootstrap core JavaScript
	================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<!-- Graphs -->
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
	<script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.10.16/fh-3.1.3/r-2.2.1/sl-1.2.5/datatables.min.js"></script>
	<script src="~/js/accordion.js"></script>
	<script>

		//$(document).ready(function () {
		//	$('#pitchersTable').DataTable()
		//});

		$(document).ready(function () {
			$('#pitchersTable').DataTable({
				"ordering": true,
				"paging": true,
				"FixedHeader": true,
				"fixedColumns": true
			});

			$("input[name='franchiseId']:radio").change(function () {
				var value = $(this).val();
				alert(value);

			});

			var span = document.getElementsByName("franchiseId");
			var inputs = span.getElementsByTagName("input");
			for (var i = 0; i < inputs.length; ++i) {
				if (inputs[i].checked) {
					var i = inputs[i].value;
					alert(i);
				}
			}


		});

		// Add event listener for opening and closing details
		$('#pitchersTable tbody').on('click', 'td.details-control', function () {
			var table = $('#pitchersTable').DataTable();
			var tr = $(this).closest('tr');
			var tdi = tr.find("i.fa");
			var row = table.row(tr);

			if (tr.hasClass('dropPlayer')) {
				//tdi.first().hasClass('addPlayer'))
				//tr.removeClass('addPlayer');
				tdi.first().removeClass('fa-minus-square');
				tdi.first().addClass('fa-plus-square');
				tr.removeClass('dropPlayer');


			}
			else {
				// Open this row
				//row.child(format(row.data())).show();
				tr.addClass('dropPlayer');

				tdi.first().removeClass('fa-plus-square');
				tdi.first().addClass('fa-minus-square');

			}
		});

		//	}
		//});
	</script>

	<script>
		function openNav() {
			document.getElementById("mySidenav").style.width = "250px";
			document.getElementById("main").style.marginLeft = "250px";
			document.body.style.backgroundColor = "rgba(0,0,0,0.4)";
		}

		function closeNav() {
			document.getElementById("mySidenav").style.width = "0";
			document.getElementById("main").style.marginLeft = "0";
			document.body.style.backgroundColor = "white";
		}																														//	if ($(cell.node()).hasClass("details-control")) {
		$('.panel-collapse').on('hidden.bs.collapse', function () {
			// find the children and close them
			$(this).find('.collapse').collapse('hide');
		});																																																																																																																																																																																																				//		e.preventDefault();


	</script>
	<script src="~/js/players.js">



	</script>
</body>
</html>