SalaryCapGame/ViewModels/Franchise/EditFranchiseModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SalaryCapGame.ViewModels
{
    public class EditFranchiseModel
    {
        public int OwnerId { get; set; }
        [Required]
        [Display( Name = "Franchise Name")]
        [MaxLength( 50 )]
        public string Name { get; set; }
        public string ImageUrl { get; set; }
    }
}

SalaryCapGame/ViewModels/Franchise/FranchiseIndexListingModel.cs
using SalaryCapData.Models;
using System.Collections.Generic;

namespace SalaryCapGame.ViewModels
{
    public class FranchiseIndexListingModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ImageUrl { get; set; }

        public int OwnerId { get; set; }
        public int LeagueId { get; set; }

        public League League { get; set; }
        public Owner Owner { get; set; }

        public long Points { get; set; }
        public decimal Value { get; set; }
        public int NumberOfTrades { get; set; }

    }
}

SalaryCapGame/ViewModels/Franchise/FranchiseIndexModel.cs
using System.Collections.Generic;

namespace SalaryCapGame.ViewModels
{
    public class FranchiseIndexModel
    {
        public IEnumerable<FranchiseIndexListingModel> Franchises { get; set; }
    }
}

SalaryCapGame/ViewModels/Franchise/FranchiseMenuModel.cs
using SalaryCapData.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SalaryCapGame.ViewModels
{
    public class FranchiseMenuModel
    {
        public int OwnerId { get; set; }
        public string FullName { get; set; }
        public IEnumerable<Franchise> Franchises { get; set; }
        public IEnumerable<League> Leagues { get; set; }
    }
}

SalaryCapGame/ViewModels/Franchise/FranchiseRoster.cs
using SalaryCapData.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SalaryCapGame.ViewModels
{
	public class PlayerPositionAssignments
	{
		public PlayerAssignment Pitcher1 { get; set; }
		public PlayerAssignment Pitcher2 { get; set; }
		public PlayerAssignment Pitcher3 { get; set; }
		public PlayerAssignment Pitcher4 { get; set; }
		public PlayerAssignment Catcher { get; set; }
		public PlayerAssignment FirstBase { get; set; }
		public PlayerAssignment SecondBase { get; set; }
		public PlayerAssignment ThirdBase { get; set; }
		public PlayerAssignment Shortstop { get; set; }
		public PlayerAssignment Outfielder1 { get; set; }
		public PlayerAssignment Outfielder2 { get; set; }
		public PlayerAssignment Outfielder4 { get; set; }
		public PlayerAssignment DesignatedHitter { get; set; }
	}
}

SalaryCapGame/Controllers/FranchisesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SalaryCapData;
using SalaryCapData.Interfaces;
using SalaryCapData.Models;
using SalaryCapGame.ViewModels;

namespace SalaryCapGame.Controllers
{
	public class FranchisesController : Controller
	{
		private readonly IFranchise _franchises;
		private readonly ILeague _leagues;

		public FranchisesController( IFranchise franchises, ILeague leagues )
		{
			_franchises = franchises;
			_leagues = leagues;
		}

		// GET: Franchises
		public IActionResult Index()
		{
			var franchises = _franchises.GetAll();
			var results = franchises.Select( f => new FranchiseIndexListingModel
			{
				Id = f.Id,
				ImageUrl = f.ImageUrl,
				LeagueId = f.LeagueId,
				Name = f.Name,
				OwnerId = f.OwnerId,
				NumberOfTrades = f.NumberOfTrades,
				Points = f.Points,
				Value = f.Value
			} ).OrderBy( r => r.Points );

			return View( franchises.ToList() );
		}

		public IEnumerable<PlayerAssignment> Players( int id )
		{
			IEnumerable<PlayerAssignment> players = _franchises.Get( id ).Players;

			return players;
		}

		// GET: Franchises/Details/5
		public IActionResult Details( int id )
		{
			if ( id == 0 )
			{
				return NotFound();
			}

			var franchise = _franchises.Get( id );

			if ( franchise == null )
			{
				return NotFound();
			}

			return View( franchise );
		}

		// GET: Franchises/Create
		public IActionResult Create( int id )
		{
			//ViewData[ "LeagueId" ] = new SelectList( _leagues.GetAll(), "Id", "Name" );
			ViewData[ "Leagues" ] = BuildLeaguesList();
			var editFranchiseModel = new EditFranchiseModel
			{
				OwnerId = id,
				ImageUrl = "",
				Name = "",
			};

			//            ViewData["OwnerId"] = new SelectList(_franchises.Owners, "Id", "Email");

			return View( editFranchiseModel );
		}

		// POST: Franchises/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create( [Bind( "Id,Name,ImageUrl,LeagueId,OwnerId,DateCreated,DateModified" )] EditFranchiseModel franchiseModel, int selectedLeagueId )
		{
			if ( ModelState.IsValid )
			{
				var franchise = new Franchise
				{
					ImageUrl = franchiseModel.ImageUrl,
					Name = franchiseModel.Name,
					LeagueId = selectedLeagueId,
					OwnerId = franchiseModel.OwnerId,
					NumberOfTrades = 3,
					Value = 50
				};
				_franchises.Add( franchise );
				return RedirectToAction( nameof( Index ) );
			}
			//ViewData[ "LeagueId" ] = new SelectList( _leagues.GetAll(), "Id", "Name", franchise.LeagueId );
			// ViewData["OwnerId"] = new SelectList(_franchises.Owners, "Id", "Email", franchise.OwnerId);
			return View( franchiseModel );
		}

		// GET: Franchises/Edit/5
		public IActionResult Edit( int id )
		{
			if ( id == 0 )
			{
				return NotFound();
			}

			var franchise = _franchises.Get( id );
			if ( franchise == null )
			{
				return NotFound();
			}
			ViewData[ "LeagueId" ] = new SelectList( _leagues.GetAll(), "Id", "Name", franchise.LeagueId );
			// ViewData["OwnerId"] = new SelectList(_franchises.Owners, "Id", "Email", franchise.OwnerId);
			return View( franchise );
		}

		// POST: Franchises/Edit/5
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Edit( int id, [Bind( "Id,Name,ImageUrl,LeagueId,OwnerId,DateCreated,DateModified" )] Franchise franchise )
		{
			if ( id != franchise.Id )
			{
				return NotFound();
			}

			if ( ModelState.IsValid )
			{
				try
				{
					_franchises.Update( franchise );
				}
				catch ( DbUpdateConcurrencyException )
				{
					if ( !FranchiseExists( franchise.Id ) )
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction( nameof( Index ) );
			}
			ViewData[ "LeagueId" ] = new SelectList( _leagues.GetAll(), "Id", "Name", franchise.LeagueId );
			// ViewData["OwnerId"] = new SelectList(_franchises.Owners, "Id", "Email", franchise.OwnerId);
			return View( franchise );
		}

		//// GET: Franchises/Delete/5
		//public async Task<IActionResult> Delete(int? id)
		//{
		//    if (id == null)
		//    {
		//        return NotFound();
		//    }

		//    var franchise = await _franchises.Franchises
		//        .Include(f => f.League)
		//        .Include(f => f.Owner)
		//        .SingleOrDefaultAsync(m => m.Id == id);
		//    if (franchise == null)
		//    {
		//        return NotFound();
		//    }

		//    return View(franchise);
		//}

		//// POST: Franchises/Delete/5
		//[HttpPost, ActionName("Delete")]
		//[ValidateAntiForgeryToken]
		//public async Task<IActionResult> DeleteConfirmed(int id)
		//{
		//    var franchise = await _franchises.Franchises.SingleOrDefaultAsync(m => m.Id == id);
		//    _franchises.Franchises.Remove(franchise);
		//    await _franchises.SaveChangesAsync();
		//    return RedirectToAction(nameof(Index));
		//}

		private void PopulateLegauesDropDownList( object selectedLeague = null )
		{
			var leagues = from l in _leagues.GetAll() orderby l.Name select l;
			var selectLeagues = leagues.Select( l => new LeagueListingModel
			{
				Id = l.Id,
				NumberOfFranchises = l.Franchises.Count(),
				MaxLeagueSize = 10,
				Commissioner = l.Commissioner,
				CommissionerId = l.CommissionerId,
				Name = l.Name + " " + l.Franchises.Count().ToString() + " / " + "10 " + l.Commissioner.FirstName + " " + l.Commissioner.LastName
			} ).ToList();
			ViewData[ "LeagueId" ] = new SelectList( selectLeagues, "Id", "Name", selectedLeague );
		}

		private IEnumerable<LeagueListingModel> BuildLeaguesList( object selectedLeague = null )
		{
			var leagues = from l in _leagues.GetAll() orderby l.Name select l;
			var selectLeagues = leagues.Select( l => new LeagueListingModel
			{
				Id = l.Id,
				NumberOfFranchises = l.Franchises.Count(),
				MaxLeagueSize = 10,
				Commissioner = l.Commissioner,
				CommissionerId = l.CommissionerId,
				Name = l.Name
			} ).ToList();

			return (selectLeagues);

		}


		private bool FranchiseExists( int id )
		{
			return _franchises.Any( id );
		}
		public ActionResult AddPlayerToFranchise( int franchiseId, int playerId, int ownerId )
		{
			var j = franchiseId;
			var k = playerId;

			_franchises.AddPlayer( franchiseId, playerId );
			return RedirectToAction( "Details", "Owners", new { id = ownerId } );
		}

	}
}

SalaryCapGame/Controllers/LeagueController.cs
using Microsoft.AspNetCore.Mvc;
using SalaryCapData.Interfaces;
using SalaryCapGame.ViewModels;
using System.Linq;

namespace SalaryCapGame.Controllers
{


	public class LeagueController : Controller
	{
		private static readonly log4net.ILog log = log4net.LogManager.GetLogger( System.Reflection.MethodBase.GetCurrentMethod().DeclaringType );
		private readonly ILeague _leagues;

		public LeagueController( ILeague leagues )
		{
			_leagues = leagues;
		}

		public IActionResult Index()
		{
			var leagues = _leagues.GetAll();
			var listingResult = leagues.Select( result => new LeagueIndexListingModel
			{
				LeagueListingModel = new LeagueListingModel
				{
					Id = result.Id,
					Name = result.Name,
					CommissionerId = result.CommissionerId,
					Commissioner = result.Commissioner,
				},
				Franchises = result.Franchises

			} ).ToList();


			var model = new LeagueIndexModel()
			{
				Leagues = listingResult.ToList()
			};


			System.Diagnostics.Debug.WriteLine( "Returning from LeagueController.Index()..." );
			System.Diagnostics.Debug.WriteLine( leagues.Count() + " Leagues" );

			return View( model );
		}

		public IActionResult Detail( int id )
		{
			var leagueModel = _leagues.Get( id );
			var leagueDetail = new LeagueIndexListingModel()
			{
				LeagueListingModel = new LeagueListingModel
				{
					Id = id,
					Name = leagueModel.Name,
					Commissioner = leagueModel.Commissioner,
					CommissionerId = leagueModel.CommissionerId,
				},
				Franchises = leagueModel.Franchises.OrderByDescending( f => f.Points )
			};
			System.Diagnostics.Debug.WriteLine( "Returning from LeagueController.Detail()" );

			System.Diagnostics.Debug.WriteLine( "League is " + leagueModel.Name );
			return View( leagueDetail );
		}

		public IActionResult Summary( int id )
		{
			var leagueModel = _leagues.Get( id );
			var listingResult = new LeagueListingModel()
			{
				Id = leagueModel.Id,
				Name = leagueModel.Name,
				Commissioner = leagueModel.Commissioner

			};

			return View( leagueModel );
		}

	}
}

SalaryCapGame/Views/Partial/Franchise/FranchiseSummary.cshtml
@model IEnumerable<SalaryCapData.Models.Franchise>

@using ( Html.BeginForm() )
{


	@foreach ( var item in Model )
	{
		<tr>
			<td>
				<label><input type="radio" name="franchiseId" id="@item.Id" value="@item.Id" ); /></label>
			</td>
			<td style="text-align:left">
				<a asp-controller="Franchises" asp-action="Index" asp-route-id="@item.Id">@item.Name</a>
			</td>
			<td>
				@String.Format( "{0,6:c}", item.Value )
			</td>
			<td style="color:green;">@String.Format( "+10" )</td>
			<td>
				@String.Format( "{0,6:n}", item.Points )
			</td>
			<td style="color:red;">@String.Format( "-420" )</td>
			<td>
				@String.Format( "{0,6:g}", item.NumberOfTrades )
			</td>
			<td>

				@*<a asp-controller="League" asp-action="Detail" asp-route-id="@item.LeagueId">@item.League.Name</a>*@
			</td>
			<td>@String.Format( "3/10" )</td>
			<td style="color:green;">@String.Format( "+1" ) </td>
		</tr>

	}
}

@*<div class="row">
		<div class="col-lg-2 pull-left">

			<h4>League</h4>
		</div>
		<div class="col-lg-2 pull-left">
			<h4>Franchise</h4>
		</div>
		<div class="col-lg-2 pull-left">
			<h4>Value</h4>
		</div>
		<div class="col-lg-2 pull-left">
			<h4>Points</h4>
		</div>

	</div>
	<div class="row ">
		<div class="col-md-8 pull-left">
			@foreach ( var item in Model )
			{


				@*<td><img src="~/@Url.Content( item.ImageUrl )" class="imageCell" /></td>*@
@*<div class="row">

		<div class="col-md-3">
			<a asp-controller="League" asp-action="Detail" asp-route-id="@item.LeagueId">@item.League.Name</a>
		</div>
		<div class="col-md-3">
			<a asp-controller="Franchises" asp-action="Details" asp-route-id="@item.Id">@item.Name</a>
		</div>
		<div class="col-md-2">
			<label style="text-align:right;">@String.Format( "{0,6:c}", item.Value )</label>
		</div>
		<div class="col-md-2">
			<label style="text-align:right;">@String.Format( "{0,6:n}", item.Points )</label>
		</div>


	</div>
			}
		</div>
	</div>
	}*@

SalaryCapGame/Views/Partial/Franchise/_FranchiseHeader.cshtml
<th style="text-align:left">Franchise</th>
<th>Value</th>
<th>+/-</th>
<th>Tot. Pts</th>
<th>+/-</th>
<th>Trades</th>
<th style="text-align:left">League</th>
<th>Rank</th>
<th>+/-</th>

SalaryCapGame/Views/Partial/Franchise/_View.cshtml
@model SalaryCapGame.ViewModels.FranchiseMenuModel
@using ( Html.BeginForm() )
{
	@Html.HiddenFor( model => Model.OwnerId )
	@section FranchiseMenu
		{
		<table class="table table-striped table-sm">
			<thead>
				<tr>
					<th></th>
					<th class="glyphicon-align-left col-sm-2">
						@Html.Label( "Franchise" )
					</th>
					<th class="glyphicon-align-left col-sm-2">
						@Html.Label( "League" )
					</th>
				</tr>
			</thead>
			<tbody>
				@foreach ( var f in Model.Franchises )
				{
					<tr>
						<td class="col-sm-2">
							<div class="radio">
								<label><input type="radio" id="@f.Id" /></label>
							</div>
							@Html.ActionLink( f.Name, "Edit", "Franchises", new { f.Id }, null )
						</td>
						<td class="col-sm-2">
							@Html.ActionLink( f.League.Name, "Index", "League", new { f.LeagueId }, null )
						</td>
					</tr>
				}
			</tbody>
		</table>

	}

}